// import { ThemeProvider } from "@/components/theme-provider";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import { ConfigProvider } from "antd";

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
// import '@ant-design/v5-patch-for-react-19';
import LocaleSwitcher from "./components/LocaleSwitcher";
import Navbar from "./components/shared/Navbar";
import "./globals.css";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export async function generateStaticParams() {
  return [{ lang: "en-US" }, { lang: "bn-BD" }]; // Add all supported locales here
}

export default function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: { lang: "en-US" | "bn-BD" };
}>) {
  return (
    <html suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased `}
      >
        <ConfigProvider
          theme={{
            token: {
              colorPrimary: "#67bc45",
              colorInfo: "#67bc45",
              colorSuccess: "#2fad74",
              colorBgBase: "#ffffff",
              wireframe: true,
            },
            components: {
              Menu: {
                itemBg: "rgb(25, 101, 0)",
                itemColor: "rgba(255,255,255,0.88)",
                itemHoverColor: "rgba(255, 255, 255, 0.6)",
                itemSelectedColor: "rgb(47, 74, 173)",
                itemSelectedBg: "rgb(249,249,249)",
              },
            },
          }}
        >
          <AntdRegistry>
            <Navbar />
            <LocaleSwitcher currentLocale={params.lang} />
            {children}
          </AntdRegistry>
        </ConfigProvider>
      </body>
    </html>
  );
}
